language: php
php:
  - 5.6
  - 5.5
  - 5.4

notifications:
  email: false

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - "phpunit"
after_script: 
  - mv tests/_output/coverage.xml clover.xml 
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
