site_name: UserSystem
nav:
- 'Home': 'index.md'
- 'UserSystem':
  - 'Config.php': 'config.md'
  - 'Utils.php': 'utils.md'
  - 'Database.php': 'database.md'
  - 'UserUtils.php': 'userutils.md'
  - 'UserUsystem.php': 'usersystem.md'
docs_dir: Docs
